### ISSUE TITLE
Configuration - Could not retrieve or read configuration

### ISSUE THREAD

**Issue by cmaxwe** [mihakralj/opnsense-speedtest#1]
Installed 0.4_1 on a fresh install of OPNsense and it gives me this error via the web GUI and via command line.

$ /usr/local/opnsense/scripts/OPNsense/speedtest/speedtest --accept-license --accept-gdpr -L -fjson
[2021-03-19 14:33:25.456] [error] Configuration - Cannot retrieve configuration document (503)
[2021-03-19 14:33:25.458] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
{"type":"log","timestamp":"2021-03-19T17:33:25Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

**Comment by cmaxwe** [comment]
I think this is an error on the speedtest side actually.

Maybe the plugin should handle it more gracefully?

**Comment by mihakralj** [comment]
yes, it looks like the socket test backend didn't work for a while... Not it is back and things should work as expected.
And yes, I need a better exception handling in the wrapping code and pass the error code back to OPNsense log.
Thanks!
