### ISSUE TITLE
Requests speedtest-cli but not avalaible !

### ISSUE THREAD

**Issue by vincegre** [mihakralj/opnsense-speedtest#14]
Hi

Just installed the plugin on my DEC 740 but it asks for speedtest-cli plugin but it doesn't exist in repositories. Is it still a working plugin ? or obsolete one ?

Thanks

Vincèn

**Comment by firestormo** [comment]
***@***.***:~ # pkg search speedtest-cli
py39-speedtest-cli-2.1.3       Command line interface for testing internet bandwidth
***@***.***:~ # pkg install py39-speedtest-cli-2.1.3


Also the plugin was moved to It was moved to https://github.com/mimugmail/opn-repo

Install this repo and then install the speedtest-community plugin from there, it has the dependencies in the package. Also many more useful packages in that repo as well.

From: Vincèn ***@***.***>
Sent: Thursday, August 4, 2022 2:42 AM
To: mihakralj/opnsense-speedtest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mihakralj/opnsense-speedtest] Requests speedtest-cli but not avalaible ! (Issue #14)


Hi

Just installed the plugin on my DEC 740 but it asks for speedtest-cli plugin but it doesn't exist in repositories. Is it still a working plugin ? or obsolete one ?

Thanks

Vincèn

-

**Comment by vincegre** [comment]
Thanks @firestormo problem closed :)
