### ISSUE TITLE
Upgrading while still in "devel"

### ISSUE THREAD

**Issue by Stifler6996** [mihakralj/opnsense-speedtest#2]
Could you please post anything relevant to upgrading this (say from 0.3 to 0.5).
Is it necessary to delete first? Can it go over the top?

Thanks for the work, its mighty useful.

**Comment by mihakralj** [comment]
the package is able to clean-up and upgrade itself without de-install

**Comment by Stifler6996** [comment]
Is there an upgrade command then?
I had 0.3 installed and ran `sudo pkg add https://github.com/mihakralj/opnsense-speedtest/raw/main/work/pkg/os-speedtest-devel-0.5_1.txz`  This told me I already had the latest (0.3) installed.

I had to remove it, and then add the new version.

**Comment by mihakralj** [comment]
I just iterated a new version - but I am still struggling to understand how BSD packager decides what is a new build version and what is not...

**Comment by Stifler6996** [comment]
I still wonder how the shoelaces keep the .deb packages together. Ill leave this to you!

Perhaps make a note on the main page as a prompt for others. 👍
